services:
    web:
        environment:
            VIRTUAL_HOST: openorf.mariozechner.at
            LETSENCRYPT_HOST: openorf.mariozechner.at
            LETSENCRYPT_EMAIL: contact@mariozechner.at
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
